server:
  port: 5050
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
#nginx存放图片的路径
file:
  location:
    directory: /usr/local/learn/docker/nginx/html/


